### ISSUE TITLE
No way to use an untranslated % character in a command

### ISSUE THREAD

**Issue by chocolateboy** [sitaramc/map#2]
`map` uses `%` &c. as a special token. Some commands also use `%` as a special token e.g. [`feh`](http://feh.finalrewind.org/), which uses `%f` in its actions to denote the current filename. As a result there's no way to pipe a bunch or files to `feh` with its `--action` option because `map` turns the `%f` into the filename (e.g. `./image.png`) with an "f" appended (e.g. `./image.pngf`). So this doesn't work:

```bash
# browse downloaded images and move selected images to the Kodi image gallery.
# select images by hitting enter
kodify() {
    downloads="$HOME/downloads/pictures"
    gallery="/media/share/pictures"
    ls -tc $downloads/**/*.* | map feh --draw-filename --action "echo '%f' && mv '%f' $gallery"
}
```

As with `sprintf` and co., this can be solved by providing a way to *not* translate the `%`. Since `%%` is already spoken for, how about `%%%`?

**Comment by sitaramc** [comment]
Hi, I have *completely* rewritten map now, after some serious thought about where it is and what I want it to do.  I will be pushing a brand new "master" this weekend or maybe next weekend.  That does have the ability to do this.
